# Pytorch 60min tutorial

This notebook follows the [PyTorch ‘60min Blitz’ Tutorial](https://docs.pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html)

First we import the module we will need fo this tutorial:

In [1]:
import torch
import numpy as np

## Tensors

This section demonstrates basic tensor operations. We start with initialization, using the four following functions:
* `torch.tensor` to create a tensor from a Python list,
* `torch.from_mumpy` to create a tensor from a NumPy array,
* `torch.zeros` or `torch.zeros_like` to create a tensor filled with ones,
* `torch.ones` or `torch.ones_like` to create a tensor filled with ones,
* `torch.rand` or `torch.rand_like` to create a tensor filled with random values.

In [2]:
data = [[1,2],[3,4]]
shape = (2, 3, )
data_np = np.array(data)

x_data = torch.tensor(data)
x_np = torch.from_numpy(data_np)
x_zeros = torch.zeros(shape)
x_ones = torch.ones(shape)
x_rand = torch.rand(shape)
x_zeros_b = torch.zeros_like(x_data)
x_ones_b = torch.ones_like(x_data)
x_rand_b = torch.rand_like(x_data, dtype=torch.float)

print(f'x_data:\n {x_data}\n')
print(f'x_np:\n {x_np}\n')
print(f'x_zeros:\n {x_zeros}\n')
print(f'x_ones:\n {x_ones}\n')
print(f'x_rand:\n {x_rand}\n')
print(f'x_zeros_b:\n {x_zeros_b}\n')
print(f'x_ones_b:\n {x_ones_b}\n')
print(f'x_rand_b:\n {x_rand_b}\n')

x_data:
 tensor([[1, 2],
        [3, 4]])

x_np:
 tensor([[1, 2],
        [3, 4]])

x_zeros:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])

x_ones:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])

x_rand:
 tensor([[0.9237, 0.4951, 0.0481],
        [0.0502, 0.6592, 0.3677]])

x_zeros_b:
 tensor([[0, 0],
        [0, 0]])

x_ones_b:
 tensor([[1, 1],
        [1, 1]])

x_rand_b:
 tensor([[0.1651, 0.4022],
        [0.9290, 0.2393]])



Three important tensor attributes are:
* `shape`: the tensor shape,
* `dtype`: the tensor data type,
* `device`: the device the tensor is stored in (`cpu` stands for the host; the tensor may technically be stored in RAM).

In [3]:
tensor = torch.rand(shape)
print(f'tensor has shape: {tensor.shape}')
print(f'tensor has data type: {tensor.dtype}')
print(f'tensor is stored on device: {tensor.device}')

tensor has shape: torch.Size([2, 3])
tensor has data type: torch.float32
tensor is stored on device: cpu


Tensor operations are listed in the [reference API documentation](https://docs.pytorch.org/docs/stable/torch.html). We here only demonstrate a few important ones:
* The member function `to` sends the tensor to a specific device.
* NumPy-like indexing can be used to take a slice of a tensor.
* The function `cat` concatenates tensors along a specified dimension.
* Element-wise arithmetic operations can be expressed using the binary operators `+`, `-`, `*`, ... Alternatively, one can use the member functions `add`, `sub`, `mul`, ...
* The member function `T` returns the transpose of a 2-dimensional tensor.
* The binary operator `@` denotes matrix multiplication. Alternatively, one can use the member function `matmul`.
* In-place operations have a `_` suffix.

In [4]:
print(f'tensor:\n {tensor}\n')

# Move the tensor to GPU if available
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
print(f'tensor is stored on device: {tensor.device}\n')

# NumPy-like indexing
print(f'Column 1: {tensor[:,1]}\n')

# Join the tensor with itself along dimension 1
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

# Element-wise product
print(f'Hadamard multiplication of tensor with itself:\n {tensor * tensor}\n')

# Matrix multiplication of tensor and its transpose
print(f'Matrix multiplication of tensor and its transpose:\n {tensor @ tensor.T}\n')

# Multiply by 10 in-place
tensor.mul_(10)
print(f'Multiplication by 10:\n {tensor}\n')

tensor:
 tensor([[0.0839, 0.6956, 0.9220],
        [0.7288, 0.6149, 0.1720]])

tensor is stored on device: cpu

Column 1: tensor([0.6956, 0.6149])

tensor([[0.0839, 0.6956, 0.9220, 0.0839, 0.6956, 0.9220, 0.0839, 0.6956, 0.9220],
        [0.7288, 0.6149, 0.1720, 0.7288, 0.6149, 0.1720, 0.7288, 0.6149, 0.1720]])
Hadamard multiplication of tensor with itself:
 tensor([[0.0070, 0.4839, 0.8502],
        [0.5312, 0.3781, 0.0296]])

Matrix multiplication of tensor and its transpose:
 tensor([[1.3411, 0.6474],
        [0.6474, 0.9388]])

Multiplication by 10:
 tensor([[0.8385, 6.9560, 9.2204],
        [7.2880, 6.1489, 1.7202]])



Tensors stored on the host memory (`cpu`) can share physical memory locations with NumPy arrays; they are then like two representations of the same entities and changing one will change the other. 

Demonstration of creating a NumPy array from a tensor using the member function `numpy`:

In [6]:
# Create a tensor
tensor = torch.ones((5,5,))
print(f'tensor:\n {tensor}\n')

# Create a NumPy array sharing the tensor's memory location
array = tensor.numpy()
print(f'array:\n {array}\n')

# Change the tensor
tensor.add_(1)
print(f'tensor:\n {tensor}\n')
print(f'array:\n {array}\n')

# Change the array
array += 1
print(f'tensor:\n {tensor}\n')
print(f'array:\n {array}\n')

tensor:
 tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

array:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

tensor:
 tensor([[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]])

array:
 [[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]

tensor:
 tensor([[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]])

array:
 [[3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]]



Conversely, a tensor can be created from a NumPy array using `torch.from_numpy`:

In [8]:
# Create a NumPy array
array = np.ones((5,5,))
print(f'array:\n {array}\n')

# Create a tensor charing the array's memory location
tensor = torch.from_numpy(array)
print(f'tensor:\n {tensor}\n')

# Change the array
array += 1
print(f'array:\n {array}\n')
print(f'tensor:\n {tensor}\n')

# Change the tensor
tensor.add_(1)
print(f'array:\n {array}\n')
print(f'tensor:\n {tensor}\n')

array:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

tensor:
 tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)

array:
 [[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]

tensor:
 tensor([[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]], dtype=torch.float64)

array:
 [[3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]]

tensor:
 tensor([[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]], dtype=torch.float64)



## A Gentle Introduction to `torch.autograd`

## Neural Networks

## Training a CLassifier